version: '2'

services:
    admin:
      build:  
        dockerfile: Dockerfile
        context: admin/
      ports: "8080:8080"
    backend:
      build:  
        dockerfile: Dockerfile
        context: backend/
      ports: "4000:4000"
    frontend:
      build:  
        dockerfile: Dockerfile
        context: frontend/
      ports: "3000:3000"