name: build_image
on: 
    push:
        branches: [ main ]
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_ACCESSTOKEN}}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1
              id: buildx
            
            - name: Build and Push Docker Image Admin
              uses: docker/build-push-action@v2
              with: 
                context: ././admin
                file: ./Dockerfile
                builder: ${{ steps.buildx.outputs.name}}
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME}}/admin

            - name: Verify
              run: echo ${{ steps.docker_build.outputs.digest }}
